language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

install:
  - wget https://phar.phpunit.de/phpunit-old.phar
  - composer install

script:
  - php phpunit-old.phar

notifications:
  email: false
