language: php

php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

install:
  - wget https://phar.phpunit.de/phpunit-5.7.phar
  - composer install

script:
  - php phpunit-5.7.phar

notifications:
  email: false
